[package]
name = "orka"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "orka"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
ignore = "0.4"
libc = "0.2"
noyalib = "0.0.17"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
walkdir = "2"
