[package]
name = "orka"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "orka"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
clap = { version = "4", features = ["derive"] }
ignore = "0.4"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_yml = "0.0"
tempfile = "3"
walkdir = "2"
